spin_manifest_version = 2

[application]
name = "spin-hello-ts"
version = "0.1.0"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "spin-hello-ts"

[[trigger.http]]
route = "/..."
executor = { type = "wagi" } # Note: We are running this using the Wagi spec
component = "spin-hello-ts"

[component.spin-hello-ts]
source = "build/optimized.wasm"
